export const locations = [
  // =========================================
  // 1. KOTA & KABUPATEN UTAMA (PRIORITAS)
  // =========================================
  
  // --- DKI JAKARTA ---
  { slug: "jakarta-pusat", name: "Jakarta Pusat", type: "Kota Administrasi" },
  { slug: "jakarta-utara", name: "Jakarta Utara", type: "Kota Administrasi" },
  { slug: "jakarta-barat", name: "Jakarta Barat", type: "Kota Administrasi" },
  { slug: "jakarta-selatan", name: "Jakarta Selatan", type: "Kota Administrasi" },
  { slug: "jakarta-timur", name: "Jakarta Timur", type: "Kota Administrasi" },
  { slug: "kepulauan-seribu", name: "Kepulauan Seribu", type: "Kabupaten" },

  // --- JAWA BARAT (KOTA) ---
  { slug: "bandung", name: "Bandung", type: "Kota" },
  { slug: "bogor", name: "Bogor", type: "Kota" },
  { slug: "bekasi", name: "Bekasi", type: "Kota" },
  { slug: "depok", name: "Depok", type: "Kota" },
  { slug: "cimahi", name: "Cimahi", type: "Kota" },
  { slug: "tasikmalaya", name: "Tasikmalaya", type: "Kota" },
  { slug: "cirebon", name: "Cirebon", type: "Kota" },
  { slug: "sukabumi", name: "Sukabumi", type: "Kota" },
  { slug: "banjar", name: "Banjar", type: "Kota" },

  // --- JAWA BARAT (KABUPATEN) ---
  { slug: "kabupaten-bandung", name: "Kabupaten Bandung", type: "Kabupaten" },
  { slug: "kabupaten-bandung-barat", name: "Bandung Barat", type: "Kabupaten" },
  { slug: "kabupaten-bekasi", name: "Bekasi", type: "Kabupaten" },
  { slug: "kabupaten-bogor", name: "Bogor", type: "Kabupaten" },
  { slug: "kabupaten-ciamis", name: "Ciamis", type: "Kabupaten" },
  { slug: "kabupaten-cianjur", name: "Cianjur", type: "Kabupaten" },
  { slug: "kabupaten-cirebon", name: "Cirebon", type: "Kabupaten" },
  { slug: "kabupaten-garut", name: "Garut", type: "Kabupaten" },
  { slug: "kabupaten-indramayu", name: "Indramayu", type: "Kabupaten" },
  { slug: "kabupaten-karawang", name: "Karawang", type: "Kabupaten" },
  { slug: "kabupaten-kuningan", name: "Kuningan", type: "Kabupaten" },
  { slug: "kabupaten-majalengka", name: "Majalengka", type: "Kabupaten" },
  { slug: "kabupaten-pangandaran", name: "Pangandaran", type: "Kabupaten" },
  { slug: "kabupaten-purwakarta", name: "Purwakarta", type: "Kabupaten" },
  { slug: "kabupaten-subang", name: "Subang", type: "Kabupaten" },
  { slug: "kabupaten-sukabumi", name: "Sukabumi", type: "Kabupaten" },
  { slug: "kabupaten-sumedang", name: "Sumedang", type: "Kabupaten" },
  { slug: "kabupaten-tasikmalaya", name: "Tasikmalaya", type: "Kabupaten" },

  // --- BANTEN ---
  { slug: "tangerang", name: "Tangerang", type: "Kota" },
  { slug: "tangerang-selatan", name: "Tangerang Selatan", type: "Kota" },
  { slug: "serang", name: "Serang", type: "Kota" },
  { slug: "cilegon", name: "Cilegon", type: "Kota" },
  { slug: "kabupaten-tangerang", name: "Kabupaten Tangerang", type: "Kabupaten" },
  { slug: "kabupaten-serang", name: "Kabupaten Serang", type: "Kabupaten" },
  { slug: "kabupaten-lebak", name: "Lebak", type: "Kabupaten" },
  { slug: "kabupaten-pandeglang", name: "Pandeglang", type: "Kabupaten" },

  // --- JAWA TENGAH ---
  { slug: "semarang", name: "Semarang", type: "Kota" },
  { slug: "surakarta", name: "Surakarta (Solo)", type: "Kota" },
  { slug: "salatiga", name: "Salatiga", type: "Kota" },
  { slug: "magelang", name: "Magelang", type: "Kota" },
  { slug: "pekalongan", name: "Pekalongan", type: "Kota" },
  { slug: "tegal", name: "Tegal", type: "Kota" },
  { slug: "kabupaten-banyumas", name: "Banyumas (Purwokerto)", type: "Kabupaten" },
  { slug: "kabupaten-batang", name: "Batang", type: "Kabupaten" },
  { slug: "kabupaten-blora", name: "Blora", type: "Kabupaten" },
  { slug: "kabupaten-boyolali", name: "Boyolali", type: "Kabupaten" },
  { slug: "kabupaten-brebes", name: "Brebes", type: "Kabupaten" },
  { slug: "kabupaten-cilacap", name: "Cilacap", type: "Kabupaten" },
  { slug: "kabupaten-demak", name: "Demak", type: "Kabupaten" },
  { slug: "kabupaten-jepara", name: "Jepara", type: "Kabupaten" },
  { slug: "kabupaten-karanganyar", name: "Karanganyar", type: "Kabupaten" },
  { slug: "kabupaten-kebumen", name: "Kebumen", type: "Kabupaten" },
  { slug: "kabupaten-kendal", name: "Kendal", type: "Kabupaten" },
  { slug: "kabupaten-klaten", name: "Klaten", type: "Kabupaten" },
  { slug: "kabupaten-kudus", name: "Kudus", type: "Kabupaten" },
  { slug: "kabupaten-pati", name: "Pati", type: "Kabupaten" },
  { slug: "kabupaten-pekalongan", name: "Pekalongan", type: "Kabupaten" },
  { slug: "kabupaten-pemalang", name: "Pemalang", type: "Kabupaten" },
  { slug: "kabupaten-purbalingga", name: "Purbalingga", type: "Kabupaten" },
  { slug: "kabupaten-purworejo", name: "Purworejo", type: "Kabupaten" },
  { slug: "kabupaten-rembang", name: "Rembang", type: "Kabupaten" },
  { slug: "kabupaten-semarang", name: "Ungaran", type: "Kabupaten" },
  { slug: "kabupaten-sragen", name: "Sragen", type: "Kabupaten" },
  { slug: "kabupaten-sukoharjo", name: "Sukoharjo", type: "Kabupaten" },
  { slug: "kabupaten-tegal", name: "Slawi", type: "Kabupaten" },
  { slug: "kabupaten-wonogiri", name: "Wonogiri", type: "Kabupaten" },
  { slug: "kabupaten-wonosobo", name: "Wonosobo", type: "Kabupaten" },

  // --- YOGYAKARTA ---
  { slug: "yogyakarta", name: "Yogyakarta", type: "Kota" },
  { slug: "sleman", name: "Sleman", type: "Kabupaten" },
  { slug: "bantul", name: "Bantul", type: "Kabupaten" },
  { slug: "kulon-progo", name: "Kulon Progo", type: "Kabupaten" },
  { slug: "gunungkidul", name: "Gunungkidul", type: "Kabupaten" },

  // --- JAWA TIMUR ---
  { slug: "surabaya", name: "Surabaya", type: "Kota" },
  { slug: "malang", name: "Malang", type: "Kota" },
  { slug: "madiun", name: "Madiun", type: "Kota" },
  { slug: "kediri", name: "Kediri", type: "Kota" },
  { slug: "mojokerto", name: "Mojokerto", type: "Kota" },
  { slug: "blitar", name: "Blitar", type: "Kota" },
  { slug: "pasuruan", name: "Pasuruan", type: "Kota" },
  { slug: "probolinggo", name: "Probolinggo", type: "Kota" },
  { slug: "batu", name: "Batu", type: "Kota" },
  { slug: "kabupaten-banyuwangi", name: "Banyuwangi", type: "Kabupaten" },
  { slug: "kabupaten-bojonegoro", name: "Bojonegoro", type: "Kabupaten" },
  { slug: "kabupaten-gresik", name: "Gresik", type: "Kabupaten" },
  { slug: "kabupaten-jember", name: "Jember", type: "Kabupaten" },
  { slug: "kabupaten-jombang", name: "Jombang", type: "Kabupaten" },
  { slug: "kabupaten-lamongan", name: "Lamongan", type: "Kabupaten" },
  { slug: "kabupaten-madiun", name: "Madiun", type: "Kabupaten" },
  { slug: "kabupaten-magetan", name: "Magetan", type: "Kabupaten" },
  { slug: "kabupaten-malang", name: "Kepanjen", type: "Kabupaten" },
  { slug: "kabupaten-nganjuk", name: "Nganjuk", type: "Kabupaten" },
  { slug: "kabupaten-ngawi", name: "Ngawi", type: "Kabupaten" },
  { slug: "kabupaten-pacitan", name: "Pacitan", type: "Kabupaten" },
  { slug: "kabupaten-pamekasan", name: "Pamekasan", type: "Kabupaten" },
  { slug: "kabupaten-ponorogo", name: "Ponorogo", type: "Kabupaten" },
  { slug: "kabupaten-sidoarjo", name: "Sidoarjo", type: "Kabupaten" },
  { slug: "kabupaten-tuban", name: "Tuban", type: "Kabupaten" },
  { slug: "kabupaten-tulungagung", name: "Tulungagung", type: "Kabupaten" },

  // --- BALI & NUSA TENGGARA ---
  { slug: "denpasar", name: "Denpasar", type: "Kota" },
  { slug: "kabupaten-badung", name: "Badung", type: "Kabupaten" },
  { slug: "kabupaten-buleleng", name: "Buleleng", type: "Kabupaten" },
  { slug: "kabupaten-gianyar", name: "Gianyar", type: "Kabupaten" },
  { slug: "kabupaten-tabanan", name: "Tabanan", type: "Kabupaten" },
  { slug: "mataram", name: "Mataram", type: "Kota" },
  { slug: "kupang", name: "Kupang", type: "Kota" },

  // --- SUMATERA ---
  { slug: "medan", name: "Medan", type: "Kota" },
  { slug: "palembang", name: "Palembang", type: "Kota" },
  { slug: "bandar-lampung", name: "Bandar Lampung", type: "Kota" },
  { slug: "batam", name: "Batam", type: "Kota" },
  { slug: "pekanbaru", name: "Pekanbaru", type: "Kota" },
  { slug: "padang", name: "Padang", type: "Kota" },
  { slug: "jambi", name: "Jambi", type: "Kota" },
  { slug: "bengkulu", name: "Bengkulu", type: "Kota" },
  { slug: "dumai", name: "Dumai", type: "Kota" },
  { slug: "binjai", name: "Binjai", type: "Kota" },
  { slug: "banda-aceh", name: "Banda Aceh", type: "Kota" },
  { slug: "tanjung-pinang", name: "Tanjung Pinang", type: "Kota" },
  { slug: "pangkal-pinang", name: "Pangkal Pinang", type: "Kota" },

  // --- KALIMANTAN ---
  { slug: "pontianak", name: "Pontianak", type: "Kota" },
  { slug: "banjarmasin", name: "Banjarmasin", type: "Kota" },
  { slug: "balikpapan", name: "Balikpapan", type: "Kota" },
  { slug: "samarinda", name: "Samarinda", type: "Kota" },
  { slug: "palangka-raya", name: "Palangka Raya", type: "Kota" },
  { slug: "banjarbaru", name: "Banjarbaru", type: "Kota" },
  { slug: "singkawang", name: "Singkawang", type: "Kota" },
  { slug: "bontang", name: "Bontang", type: "Kota" },

  // --- SULAWESI ---
  { slug: "makassar", name: "Makassar", type: "Kota" },
  { slug: "manado", name: "Manado", type: "Kota" },
  { slug: "palu", name: "Palu", type: "Kota" },
  { slug: "kendari", name: "Kendari", type: "Kota" },
  { slug: "gorontalo", name: "Gorontalo", type: "Kota" },
  { slug: "parepare", name: "Parepare", type: "Kota" },

  // ==============================================================
  // 2. KECAMATAN (FOKUS AREA BISNIS UTAMA) - Local SEO Booster
  // ==============================================================

  // --- KOTA BANDUNG (Lengkap) ---
  { slug: "andir-bandung", name: "Andir", type: "Kecamatan (Bandung)" },
  { slug: "astana-anyar-bandung", name: "Astana Anyar", type: "Kecamatan (Bandung)" },
  { slug: "antapani-bandung", name: "Antapani", type: "Kecamatan (Bandung)" },
  { slug: "arcamanik-bandung", name: "Arcamanik", type: "Kecamatan (Bandung)" },
  { slug: "babakan-ciparay-bandung", name: "Babakan Ciparay", type: "Kecamatan (Bandung)" },
  { slug: "bandung-kidul", name: "Bandung Kidul", type: "Kecamatan (Bandung)" },
  { slug: "bandung-kulon", name: "Bandung Kulon", type: "Kecamatan (Bandung)" },
  { slug: "bandung-wetan", name: "Bandung Wetan", type: "Kecamatan (Bandung)" },
  { slug: "batununggal-bandung", name: "Batununggal", type: "Kecamatan (Bandung)" },
  { slug: "bojongloa-kaler-bandung", name: "Bojongloa Kaler", type: "Kecamatan (Bandung)" },
  { slug: "bojongloa-kidul-bandung", name: "Bojongloa Kidul", type: "Kecamatan (Bandung)" },
  { slug: "buahbatu-bandung", name: "Buahbatu", type: "Kecamatan (Bandung)" },
  { slug: "cibeunying-kaler-bandung", name: "Cibeunying Kaler", type: "Kecamatan (Bandung)" },
  { slug: "cibeunying-kidul-bandung", name: "Cibeunying Kidul", type: "Kecamatan (Bandung)" },
  { slug: "cibiru-bandung", name: "Cibiru", type: "Kecamatan (Bandung)" },
  { slug: "cicendo-bandung", name: "Cicendo", type: "Kecamatan (Bandung)" },
  { slug: "cidadap-bandung", name: "Cidadap", type: "Kecamatan (Bandung)" },
  { slug: "cinambo-bandung", name: "Cinambo", type: "Kecamatan (Bandung)" },
  { slug: "coblong-bandung", name: "Coblong", type: "Kecamatan (Bandung)" },
  { slug: "gedebage-bandung", name: "Gedebage", type: "Kecamatan (Bandung)" },
  { slug: "kiaracondong-bandung", name: "Kiaracondong", type: "Kecamatan (Bandung)" },
  { slug: "lengkong-bandung", name: "Lengkong", type: "Kecamatan (Bandung)" },
  { slug: "mandalajati-bandung", name: "Mandalajati", type: "Kecamatan (Bandung)" },
  { slug: "panyileukan-bandung", name: "Panyileukan", type: "Kecamatan (Bandung)" },
  { slug: "rancasari-bandung", name: "Rancasari", type: "Kecamatan (Bandung)" },
  { slug: "regol-bandung", name: "Regol", type: "Kecamatan (Bandung)" },
  { slug: "sukajadi-bandung", name: "Sukajadi", type: "Kecamatan (Bandung)" },
  { slug: "sukasari-bandung", name: "Sukasari", type: "Kecamatan (Bandung)" },
  { slug: "sumur-bandung", name: "Sumur Bandung", type: "Kecamatan (Bandung)" },
  { slug: "ujung-berung-bandung", name: "Ujung Berung", type: "Kecamatan (Bandung)" },

  // --- KABUPATEN BANDUNG (Area Soreang & Sekitarnya) ---
  { slug: "soreang", name: "Soreang", type: "Kecamatan (Kab. Bandung)" },
  { slug: "kopo", name: "Kopo (Kecamatan)", type: "Kecamatan" },
  { slug: "margahayu", name: "Margahayu", type: "Kecamatan (Kab. Bandung)" },
  { slug: "margaasih", name: "Margaasih", type: "Kecamatan (Kab. Bandung)" },
  { slug: "katapang", name: "Katapang", type: "Kecamatan (Kab. Bandung)" },
  { slug: "dayeuhkolot", name: "Dayeuhkolot", type: "Kecamatan (Kab. Bandung)" },
  { slug: "baleendah", name: "Baleendah", type: "Kecamatan (Kab. Bandung)" },
  { slug: "banjaran", name: "Banjaran", type: "Kecamatan (Kab. Bandung)" },
  { slug: "bojongsoang", name: "Bojongsoang", type: "Kecamatan (Kab. Bandung)" },
  { slug: "cileunyi", name: "Cileunyi", type: "Kecamatan (Kab. Bandung)" },
  { slug: "ciparay", name: "Ciparay", type: "Kecamatan (Kab. Bandung)" },
  { slug: "ciwidey", name: "Ciwidey", type: "Kecamatan (Kab. Bandung)" },
  { slug: "pangalengan", name: "Pangalengan", type: "Kecamatan (Kab. Bandung)" },
  { slug: "rancaekek", name: "Rancaekek", type: "Kecamatan (Kab. Bandung)" },
  { slug: "majalaya", name: "Majalaya", type: "Kecamatan (Kab. Bandung)" },
  { slug: "nagreg", name: "Nagreg", type: "Kecamatan (Kab. Bandung)" },

  // --- JAKARTA PUSAT (Kecamatan) ---
  { slug: "gambir", name: "Gambir", type: "Kecamatan (Jakpus)" },
  { slug: "tanah-abang", name: "Tanah Abang", type: "Kecamatan (Jakpus)" },
  { slug: "menteng", name: "Menteng", type: "Kecamatan (Jakpus)" },
  { slug: "senen", name: "Senen", type: "Kecamatan (Jakpus)" },
  { slug: "cempaka-putih", name: "Cempaka Putih", type: "Kecamatan (Jakpus)" },
  { slug: "johar-baru", name: "Johar Baru", type: "Kecamatan (Jakpus)" },
  { slug: "kemayoran", name: "Kemayoran", type: "Kecamatan (Jakpus)" },
  { slug: "sawah-besar", name: "Sawah Besar", type: "Kecamatan (Jakpus)" },

  // --- JAKARTA SELATAN (Kecamatan) ---
  { slug: "kebayoran-baru", name: "Kebayoran Baru", type: "Kecamatan (Jaksel)" },
  { slug: "kebayoran-lama", name: "Kebayoran Lama", type: "Kecamatan (Jaksel)" },
  { slug: "pesanggrahan", name: "Pesanggrahan", type: "Kecamatan (Jaksel)" },
  { slug: "cilandak", name: "Cilandak", type: "Kecamatan (Jaksel)" },
  { slug: "pasar-minggu", name: "Pasar Minggu", type: "Kecamatan (Jaksel)" },
  { slug: "jagakarsa", name: "Jagakarsa", type: "Kecamatan (Jaksel)" },
  { slug: "mampang-prapatan", name: "Mampang Prapatan", type: "Kecamatan (Jaksel)" },
  { slug: "pancoran", name: "Pancoran", type: "Kecamatan (Jaksel)" },
  { slug: "tebet", name: "Tebet", type: "Kecamatan (Jaksel)" },
  { slug: "setiabudi", name: "Setiabudi", type: "Kecamatan (Jaksel)" },

  // --- JAKARTA UTARA (Kecamatan) ---
  { slug: "penjaringan", name: "Penjaringan", type: "Kecamatan (Jakut)" },
  { slug: "tanjung-priok", name: "Tanjung Priok", type: "Kecamatan (Jakut)" },
  { slug: "kelapa-gading", name: "Kelapa Gading", type: "Kecamatan (Jakut)" },
  { slug: "cilincing", name: "Cilincing", type: "Kecamatan (Jakut)" },
  { slug: "pademangan", name: "Pademangan", type: "Kecamatan (Jakut)" },
  { slug: "koja", name: "Koja", type: "Kecamatan (Jakut)" },

  // --- JAKARTA BARAT (Kecamatan) ---
  { slug: "cengkareng", name: "Cengkareng", type: "Kecamatan (Jakbar)" },
  { slug: "grogol-petamburan", name: "Grogol Petamburan", type: "Kecamatan (Jakbar)" },
  { slug: "kalideres", name: "Kalideres", type: "Kecamatan (Jakbar)" },
  { slug: "kebon-jeruk", name: "Kebon Jeruk", type: "Kecamatan (Jakbar)" },
  { slug: "kembangan", name: "Kembangan", type: "Kecamatan (Jakbar)" },
  { slug: "palmerah", name: "Palmerah", type: "Kecamatan (Jakbar)" },
  { slug: "taman-sari", name: "Taman Sari", type: "Kecamatan (Jakbar)" },
  { slug: "tambora", name: "Tambora", type: "Kecamatan (Jakbar)" },

  // --- JAKARTA TIMUR (Kecamatan) ---
  { slug: "matraman", name: "Matraman", type: "Kecamatan (Jaktim)" },
  { slug: "pulo-gadung", name: "Pulo Gadung", type: "Kecamatan (Jaktim)" },
  { slug: "jatinegara", name: "Jatinegara", type: "Kecamatan (Jaktim)" },
  { slug: "duren-sawit", name: "Duren Sawit", type: "Kecamatan (Jaktim)" },
  { slug: "kramat-jati", name: "Kramat Jati", type: "Kecamatan (Jaktim)" },
  { slug: "makasar", name: "Makasar", type: "Kecamatan (Jaktim)" },
  { slug: "pasar-rebo", name: "Pasar Rebo", type: "Kecamatan (Jaktim)" },
  { slug: "ciracas", name: "Ciracas", type: "Kecamatan (Jaktim)" },
  { slug: "cipayung", name: "Cipayung", type: "Kecamatan (Jaktim)" },
  { slug: "cakung", name: "Cakung", type: "Kecamatan (Jaktim)" },

  // --- BODETABEK (Kecamatan Populer) ---
  { slug: "serpong", name: "Serpong", type: "Kecamatan (Tangsel)" },
  { slug: "serpong-utara", name: "Serpong Utara", type: "Kecamatan (Tangsel)" },
  { slug: "ciputat", name: "Ciputat", type: "Kecamatan (Tangsel)" },
  { slug: "pamulang", name: "Pamulang", type: "Kecamatan (Tangsel)" },
  { slug: "pondok-aren", name: "Pondok Aren", type: "Kecamatan (Tangsel)" },
  { slug: "kelapa-dua", name: "Kelapa Dua", type: "Kecamatan (Tangerang)" },
  { slug: "cikupa", name: "Cikupa", type: "Kecamatan (Tangerang)" },
  { slug: "balaraja", name: "Balaraja", type: "Kecamatan (Tangerang)" },
  { slug: "cikarang-pusat", name: "Cikarang Pusat", type: "Kecamatan (Bekasi)" },
  { slug: "cikarang-barat", name: "Cikarang Barat", type: "Kecamatan (Bekasi)" },
  { slug: "cikarang-utara", name: "Cikarang Utara", type: "Kecamatan (Bekasi)" },
  { slug: "tambun-selatan", name: "Tambun Selatan", type: "Kecamatan (Bekasi)" },
  { slug: "cibinong", name: "Cibinong", type: "Kecamatan (Bogor)" },
  { slug: "gunung-putri", name: "Gunung Putri", type: "Kecamatan (Bogor)" },
  { slug: "cileungsi", name: "Cileungsi", type: "Kecamatan (Bogor)" },
  { slug: "cimanggis", name: "Cimanggis", type: "Kecamatan (Depok)" },
  { slug: "cinere", name: "Cinere", type: "Kecamatan (Depok)" },
  { slug: "margonda", name: "Margonda (Beji)", type: "Kecamatan (Depok)" },

  // --- SURABAYA (Kecamatan) ---
  { slug: "tegalsari", name: "Tegalsari", type: "Kecamatan (Surabaya)" },
  { slug: "genteng", name: "Genteng", type: "Kecamatan (Surabaya)" },
  { slug: "gubeng", name: "Gubeng", type: "Kecamatan (Surabaya)" },
  { slug: "wonokromo", name: "Wonokromo", type: "Kecamatan (Surabaya)" },
  { slug: "sukolilo", name: "Sukolilo", type: "Kecamatan (Surabaya)" },
  { slug: "rungkut", name: "Rungkut", type: "Kecamatan (Surabaya)" },

  // --- MEDAN (Kecamatan) ---
  { slug: "medan-kota", name: "Medan Kota", type: "Kecamatan (Medan)" },
  { slug: "medan-petisah", name: "Medan Petisah", type: "Kecamatan (Medan)" },
  { slug: "medan-barat", name: "Medan Barat", type: "Kecamatan (Medan)" },
  { slug: "medan-timur", name: "Medan Timur", type: "Kecamatan (Medan)" },
];